import '../styles/globals.scss';
import type { Metadata } from 'next';
import ContentLayout from '@components/layouts/ContentLayout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <ContentLayout>{children}</ContentLayout>
      </body>
    </html>
  );
}
